# This action copy data to Repo geosdi/ran-test
name: TEST - copy repo to geosdi/ran-test/test_iononrischio

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'piazze_nazionali'
        destination_repo: 'geosdi/ran-test'
        destination_folder: 'test_iononrischio/piazze_nazionali'
        destination_branch: 'main'
        user_email: 'assistenza@gestionaleinr.it'
        user_name: 'dpc-io-non-rischio'
        commit_msg: '[INR] Update National places for map'
