# This action copy data to Repo geosdi/ran-test
name: TEST NAZ - copy repo to geosdi/ran-test/test_iononrischio

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Commit Message
      id: commit_message
      # run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      run: echo "name=message::$(git log -1 --pretty=%B)" >> $GITHUB_ENV 

    - name: Check for "Caricamento" in Commit Message
      id: check_caricamento
      run: |
        # if [[ "${{ steps.commit_message.outputs.message }}" == *"Caricamento"* ]]; then
        if [[ "${{ steps.commit_message.name }}" == *"Caricamento"* ]]; then
          echo "Commit message contains 'Caricamento'. Proceeding with the workflow."
        else
          echo "Commit message does not contain 'Caricamento'. Exiting."
          exit 1
        fi

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'piazze_nazionali/2022'
        destination_repo: 'geosdi/ran-test'
        destination_folder: 'test_iononrischio/piazze_nazionali/2022/data'
        destination_branch: 'main'
        user_email: 'assistenza@gestionaleinr.it'
        user_name: 'dpc-io-non-rischio'
        commit_msg: '[INR] Update National places for map'
