# This action copy data to Repo geosdi/ran-test
name: TEST NAZ - copy repo to geosdi/ran-test/test_iononrischio

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Commit Message
      id: commit_message
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.1
            
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_files: 'giornate_nazionali/${{ steps.commit_message.outputs.message }}/data/iononrischio_map_data.geojson'
        destination_repo: 'geosdi/ran-test'
        destination_folder: 'test_iononrischio/piazze_nazionali/${{ steps.commit_message.outputs.message }}/data'
        destination_branch: 'main'
        user_email: 'assistenza@gestionaleinr.it'
        user_name: 'dpc-io-non-rischio'
        commit_msg: '[INR] Update National places for map'
