# This action copy data to Repo geosdi/ran-test
name: TEST NAZ - copy repo to geosdi/ran-test/test_iononrischio

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Commit Message
      id: commit_message
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.1
            
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'giornate_nazionali/${{ steps.commit_message.outputs.message }}/data/'
        destination-username: 'geosdi'
        destination-repository: 'ran-test'
        destination-branch: 'main'
        destination-directory: 'test_iononrischio/piazze_nazionali/${{ steps.commit_message.outputs.message }}/data/'
        commit-username: 'dpc-io-non-rischio'
        commit-email: 'assistenza@gestionaleinr.it'
        commit-message: '[INR] Update National places for map'
